package org.disalg.met.api;

public enum SubnodeType {
    QUORUM_PEER, WORKER_SENDER, WORKER_RECEIVER,
    PREP_PROCESSOR, SYNC_PROCESSOR, COMMIT_PROCESSOR, LEARNER_HANDLER, LEARNER_HANDLER_SENDER,
    FOLLOWER_PROCESSOR
}
